### ISSUE TITLE
Autosave screenshots when test fails

### ISSUE THREAD

**Issue by tarmolov** [gemini-testing/hermione#25]
When tests are run in selenium grid and some of the tests fail, it won't be clear in some cases what's wrong with them. For example, chrome passes all tests but opera doesn't.

For debugging issues I usually run the specific browser locally. However, to run browsers like IE on my mac, I have to run VM.  So I save screenshot for these browsers. It's working approach but `saveScreenshot` command should be inserted manually in the code and it's annoying.

It'd be great if `hermione` has an option to turn such behavior on.

**Comment by arikon** [comment]
As I know, this is in the works./cc @j0tunn01.05.2016, 12:09, "Alexander Tarmolov" <notifications@github.com>:When tests are run in selenium grid and some of the tests fail, it won't be clear in some cases what's wrong with them. For example, chrome passes all tests but opera doesn't.For debugging issues I usually run the specific browser locally. However, to run browsers like IE on my mac, I have to run VM. So I save screenshot for these browsers. It's working approach but saveScreenshot command should be inserted manually in the code and it's annoying.It'd be great if hermione has an option to turn such behavior on.—You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub￼

**Comment by sipayRT** [comment]
yes, we already have this task

**Comment by tarmolov** [comment]
Cool!

**Comment by j0tunn** [comment]
`hermione-allure-reporter@1.2.1` & `hermione@0.11.4` - screenshots will be attached to failed tests
