### ISSUE TITLE
Reports for Jenkins

### ISSUE THREAD

**Issue by Anyazinovyeva** [gemini-testing/hermione#360]
Hello!

Want to run tests in the jenkins, but can't get report for Jenkins plugins for view results in build(use [Xunit plugin](https://plugins.jenkins.io/xunit)).

Mocha has special reporter [xunit](https://mochajs.org/#xunit) 
Add mochaOpts in config for Hermione like [this](https://mochajs.org/#mochaopts)

```
system: {
		mochaOpts: {
			reporter: 'xunit',
			timeout: 60000
		}
	}
```
It doesn't help, nothing change.

**Comment by j0tunn** [comment]
Hermione doesn't have xunit reporter. And it will not work through the `mochaOpts` because `mocha` used in hermione only as a test parser, not runner.
I'd suggest you to use [html-reporter](https://github.com/gemini-testing/html-reporter) and publish it via some jenkins plugin like [HTML Publisher](https://wiki.jenkins.io/display/JENKINS/HTML+Publisher+Plugin)

**Comment by Anyazinovyeva** [comment]
Do you have any ideas how I can change status of build in Jenkins if appear Error?

**Comment by j0tunn** [comment]
In case of test fail hermione exit code will be nonzero. So you status should be fail by default
