### ISSUE TITLE
Can Gemini tests be ported to hermione easily?

### ISSUE THREAD

**Issue by IlyasPatel** [gemini-testing/hermione#528]
Can Gemini tests be ported to Hermione early?

What are the differences between the two projects?

Thank you

**Comment by DudaGod** [comment]
Hello.

> Can Gemini tests be ported to Hermione early?

Yes, you can use this plugin - https://github.com/gemini-testing/hermione-gemini-migrator.

> What are the differences between the two projects?

- gemini is no longer supported, but hermione is;
- gemini is used only for visual regression testing, but hermione is not only for visual regression but also for integration testing;
- hermione tests are written using all familiar constructs like `describe` and `it` (mocha used as a parser). Gemini has its own not really comfortable api for written tests;
- hermione much more faster because it run tests in parallel in workers;
- hermione has a lot of useful plugins and API to add your custom commands which allows you to solve any of your problems;

In general, these are tools of completely different levels. Uses of hermione is much wider.
