### ISSUE TITLE
How to handle runtime errors inside a plugin

### ISSUE THREAD

**Issue by epszaw** [gemini-testing/hermione#761]
Hello!

Found a strange behavior (related to allure-framework/allure-js#655). Hermione reporter doesn't handle any uncaught error inside third-party plugins. `allure-hermione` is a plugin (like hermione html reporter) and it doesn't intercept runtime errors via `ERROR` event handler. Of course, we technically can catch the error inside the plugin, but our conventional approach in Allure team – is to delegate runtime errors to a runner, instead of adding custom handlers.

The easiest way to reproduce the issue to create simple plugin which throws an error.

**Comment by shadowusr** [comment]
Hey!

Hermione failing due to an exception in a third-party plugin is intended behavior.

I've looked through related issues and your request, and discussed the matter with our team. We've arrived at the following conclusions:

- Errors in third-party plugins should be handled within those plugins. I don't see any advantages in handling these errors in Hermione, since you should fix the errors in the plugin anyway.
- Determining how tests that were running at the moment the exception was thrown, or tests that were scheduled to run afterward, should be displayed in the report is the reporter's responsibility. Hermione provides everything you need for this: you can access all tests via TestCollection in the `AFTER_TESTS_READ` event, and the `TEST_BEGIN` event is fired every time a test starts running.
- Forcing test statuses to "failed" when a third-party plugin throws an exception is not a valid approach for several reasons. To name a few, this would break existing plugins that perform "smart" retries and plugins that gather statistics.
- If you need Hermione to stop its execution while handling an error in your plugin, you may use the `halt()` function as described [here](https://github.com/gemini-testing/hermione#halt).

I hope this helps. If you have any further questions, I'd be happy to answer them.

**Comment by fortrest-jr** [comment]
> Forcing test statuses to "failed" when a third-party plugin throws an exception is not a valid approach for several reasons. To name a few, this would break existing plugins that perform "smart" retries and plugins that gather statistics.

To clarify: this isn't about the current issue, I suggested this behavior in other discussion. But surely we should handle it in a valid way.

**Comment by epszaw** [comment]
The problem has been fixed. Thank you for clarification guys!
