### ISSUE TITLE
Methods of the object stored in hermione.ctx are not passed to the test

### ISSUE THREAD

**Issue by mknq** [gemini-testing/hermione#846]
### Verify latest release

- [X] I verified that the issue exists in the latest Hermione release

### Hermione version

8.0.5

### Reproduction steps

I add an object to `hermione.ctx` in the `BEGIN` event handler as follows:
```
hermione.ctx.object.property = 'property';
hermione.ctx.object.method = () => 'method';
```
I try using this object in my test. Turns out it has the `property` field, but not the `method` function:
```
it(async () => {
    console.log(hermione.ctx.property); // Logs "property"
    console.log(hermione.ctx.property); // Logs "undefined"
});
```

I suspect that the problem occurs when sending the `MASTER_SYNC_CONFIG` event: https://github.com/gemini-testing/hermione/blob/v8.0.5/src/utils/workers-registry.js#L124
Before sending, the object has `method`, but there is no `method` field on the handler side here: https://github.com/gemini-testing/hermione/blob/v8.0.5/src/worker/hermione-facade.js#L79

Documentation for `subprocess.send(message[, sendHandle[, options]][, callback])` for the Child Process object https://nodejs.org/api/child_process.html says:

> The message goes through serialization and parsing. The resulting message might not be the same as what is originally sent.

Is that the case, apparently? Is the object being processed and changed?

### Describe the Bug

Methods of objects passed to tests via `hermione.ctx` are absent.

### Expected Behavior

Object passed via `hermione.ctx` is received unchanged in tests, along with any methods the object had.

### Which Node.js version are you using?

18

**Comment by shadowusr** [comment]
Hey!

You're absolutely right, object methods cannot be serialized/deserialized when passing between processes and therefore are lost.

We'll make it more clear in the docs.

Can you elaborate on your use-case, perhaps you need to use another feature of hermione instead of passing objects through `hermione.ctx`.

**Comment by vitaly-kiselev-qa** [comment]
@shadowusr 
Thank you for looking at the issue.

I'll try to describe our use-case.

* Our muted autotest list is stored in an external database.
* In the `BEGIN` event handler the list is get from the database.
* In the `TEST_FAIL` event handler there is a check if the failed test is muted.

Now I see, that the list itself can be passed between `BEGIN` and `TEST_FAIL` event handlers.
But functions which process this data (for example, check whether test muted or not) — can not. 

Am I correct?

Is there any other Hermione feature I can use for this purpose?
Or I should just store functions somethere else and continue using `hermione.ctx` to transfer the data?

**Comment by shadowusr** [comment]
Thanks for providing the details, @vitaly-kiselev-qa.

I understood your use case, but it's not entirely clear to me what you'd like to achieve in the end. Why would you want to check whether the test is muted while running the test?

Generally things like tinkering with test's status (skipping or muting test) should be done in the master process and tests themselves shouldn't be aware of such machinery. Understanding your end goal would help me suggest a better workaround.

**Comment by vitaly-kiselev-qa** [comment]
@shadowusr

Sorry for being not clear.

Our goal is to skip failed tests if they are muted.
In the `TEST_FAIL` event handle we check whether the test muted or not. If it is muted we change the status to `SKIPPED`.

As a result we have the following behavior:
* a muted test passes — it has `PASSED` status;
* a muted test fails — it has `SKIPPED` status. In this case we re-check the case manually.
We do not want to have failed tests because they break our CI pipelines and our managed don't like broken pipelines :-)

**Comment by shadowusr** [comment]
You can achieve described behaviour by intercepting hermione events in the master process. Here's a short example:
```js
hermione.intercept(hermione.events.TEST_FAIL, ({event, data: test}) => {
     if (externalDataSource.shouldMute(test)) {
        return {event: hermione.events.TEST_PENDING, data: test};
    }
 
    return {event, data: test};
});
```

Does this solution satisfy your requirements?

**Comment by vitaly-kiselev-qa** [comment]
@shadowusr 
Thank you for the example.
Looks like we already use similar code taken from the Hermione documentation.

I realized that I have misleaded you. Sorry for that.

There is one more scenario we want to implement: to have information from `externalDataSource` in the test report.
The goal is to see something like 'The test is muted because of the issue <...>' in the test report.
That's why I asked about accessing `externalDataSource` in the test itself.

Again, sorry for not being clear.

**Comment by shadowusr** [comment]
@vitaly-kiselev-qa, hmm, maybe I'm misunderstanding something, but I still see no issue in doing that inside event interceptor in master process. This may look like this:

```javascript
hermione.intercept(hermione.events.TEST_FAIL, ({event, data: test}) => {
     if (externalDataSource.shouldMute(test)) {
        test.skipReason = "Muted due to " + externalDataSource.getMuteReason(test);

       // Or you may save any info to meta and use it later in your report:
       test.meta.muteReason = { reason: externalDataSource.getMuteReason(test), details: /* ... */ };

        return {event: hermione.events.TEST_PENDING, data: test};
    }
 
    return {event, data: test};
});
```

Hope I got your intentions right, if you have more questions left, I'm ready to answer =)

**Comment by vitaly-kiselev-qa** [comment]
@shadowusr 
You got it right!

But there is an issue.
Our currect Allure report plugin https://github.com/allure-framework/allure-js/tree/main/packages/allure-hermione does not pass neigher `skipReason` no `meta` to the report.
That's why we had to do it on our side via test links.

**Comment by shadowusr** [comment]
I'm glad that worked. Feel free to open a new issue if you need help in the future!
